---
language: go

go:
  - 1.8
  - tip

addons:
   apt:
     sources:
       - sourceline: 'ppa:masterminds/glide'
     packages:
       - glide

install:
  - glide install
  - go get github.com/golang/lint/golint

script:
  - make check

after_success:
  - make coverage
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - go get github.com/tcnksm/ghr
  - go get github.com/mitchellh/gox

deploy:
  - provider: script
    skip_cleanup: true
    script: make release
    on:
      tags: true
      condition: $TRAVIS_GO_VERSION =~ ^1\.8

cache:
  directories:
    - ~/.glide/cache/

notifications:
  email: false
